# Generated by Django 5.2 on 2026-03-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='type',
            field=models.CharField(choices=[('earned', 'Credits Earned'), ('redeemed', 'Credits Redeemed'), ('spent', 'Credits Spent'), ('expired', 'Credits Expired')], max_length=10),
        ),
    ]
