# Generated by Django 5.2 on 2026-03-21 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('services', '0006_listing_listing_type_listing_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_updated_1f6ffe_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_buyer_i_d04d95_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_convers_3154fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_sender__c4389c_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_created_f18bb8_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.listing'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('offer', 'Offer')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='offer_status',
            field=models.CharField(blank=True, default='pending', max_length=20),
        ),
    ]
