# Generated by Django 6.0 on 2025-12-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_alter_user_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email updates'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(blank=True, help_text='Instagram handle', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Receive push/email notifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating out of 5.00', max_digits=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_orders',
            field=models.IntegerField(default=0, help_text='Total orders placed (for buyers)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_reviews',
            field=models.IntegerField(default=0, help_text='Number of reviews received'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_sales',
            field=models.IntegerField(default=0, help_text='Total sales made (for vendors)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or description', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, help_text='Business or shop name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='Required. Must be a valid PAU email for students.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hostel',
            field=models.CharField(blank=True, help_text='Hostel or campus location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified_vendor',
            field=models.BooleanField(default=False, help_text='Check to approve this vendor (admin only)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='matric_number',
            field=models.CharField(blank=True, help_text='Optional matric number (uniqueness enforced in serializer if needed)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional phone number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default.jpg', help_text='Profile picture', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('vendor', 'Vendor')], default='student', help_text='Student can buy items, Vendor can sell items', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance in NGN', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='accounts_us_user_ty_b6cfc8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified_vendor'], name='accounts_us_is_veri_ca8935_idx'),
        ),
    ]
