# Generated by Django 5.2 on 2026-02-17 12:51

import studex.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='admission_letter',
            field=models.FileField(help_text='Admission letter or proof of enrollment', upload_to='seller_verification/admission/', validators=[studex.validators.validate_document]),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='id_document',
            field=models.FileField(help_text='Student ID card', upload_to='seller_verification/id/', validators=[studex.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default.jpg', help_text='Profile picture', null=True, upload_to='profiles/', validators=[studex.validators.validate_image]),
        ),
    ]
