# Generated by Django 5.2 on 2026-03-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emailotp_alter_sellerapplication_admission_letter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_order_count',
            field=models.IntegerField(default=0, help_text='Total completed on-platform orders (for loyalty tracking)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='completion_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='% of paid orders marked completed (used for search ranking)', max_digits=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='disclaimer_accepted',
            field=models.BooleanField(default=False, help_text='User accepted the offline transaction disclaimer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='disclaimer_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='loyalty_credits',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Redeemable credits earned from completed orders (₦100 per 5 orders)', max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='on_platform_sales',
            field=models.IntegerField(default=0, help_text='Total completed on-platform orders (for vendor badge)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vendor_badge',
            field=models.CharField(choices=[('none', 'No Badge'), ('rising', 'Rising Vendor'), ('trusted', 'Trusted Vendor'), ('top', 'Top Vendor')], default='none', help_text='Auto-assigned badge based on completed on-platform orders', max_length=20),
        ),
    ]
