# Generated by Django 5.2 on 2026-03-23 06:47

import django.db.models.deletion
import studex.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerapplication',
            name='admission_letter',
        ),
        migrations.RemoveField(
            model_name='sellerapplication',
            name='id_document',
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='id_back',
            field=models.ImageField(default='', help_text='Back of student ID card', upload_to='seller_verification/id_back/', validators=[studex.validators.validate_image]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='id_front',
            field=models.ImageField(default=' ', help_text='Front of student ID card', upload_to='seller_verification/id_front/', validators=[studex.validators.validate_image]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
