# Generated by Django 5.2 on 2026-03-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_sellerapplication_admission_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='id_back_url',
            field=models.URLField(blank=True, default='', help_text='Cloudinary URL for back of ID card', max_length=500),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='id_front_url',
            field=models.URLField(blank=True, default='', help_text='Cloudinary URL for front of ID card', max_length=500),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='seller_verification/id_back/'),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='seller_verification/id_front/'),
        ),
    ]
