# Generated by Django 5.2 on 2026-03-25 10:56

import studex.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_sellerapplication_id_back_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerapplication',
            name='id_back_url',
        ),
        migrations.RemoveField(
            model_name='sellerapplication',
            name='id_front_url',
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='id_back',
            field=models.ImageField(default='', help_text='Back of student ID card', upload_to='seller_verification/id_back/', validators=[studex.validators.validate_image]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='id_front',
            field=models.ImageField(default=' ', help_text='Front of student ID card', upload_to='seller_verification/id_front/', validators=[studex.validators.validate_image]),
            preserve_default=False,
        ),
    ]
