# Generated by Django 5.2 on 2026-03-13 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin_notification', models.BooleanField(default=False, help_text='If True, shown in Django Admin panel only')),
                ('notification_type', models.CharField(choices=[('vendor_application', 'New Vendor Application'), ('new_listing', 'New Listing Needs Approval'), ('vendor_approved', 'Vendor Account Approved'), ('vendor_revoked', 'Vendor Account Deactivated')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='Leave blank for admin-only notifications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
