# Generated by Django 5.2 on 2026-03-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_is_admin_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('vendor_application', 'New Vendor Application'), ('new_listing', 'New Listing Needs Approval'), ('vendor_approved', 'Vendor Account Approved'), ('vendor_revoked', 'Vendor Account Deactivated'), ('new_booking_request', 'New Booking Request'), ('booking_paid', 'Booking Paid'), ('order_confirmed', 'Order Confirmed by Buyer'), ('booking_confirmed', 'Booking Confirmed by Vendor'), ('booking_cancelled', 'Booking Cancelled'), ('payment_received', 'Payment Received'), ('order_completed', 'Order Completed')], max_length=30),
        ),
    ]
