# Generated by Django 5.2 on 2026-03-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='paystack_response',
            new_name='flw_response',
        ),
        migrations.RenameField(
            model_name='sellerbankaccount',
            old_name='paystack_subaccount_code',
            new_name='flw_subaccount_id',
        ),
    ]
