# Generated by Django 5.2 on 2026-03-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymenttransaction_flw_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
