# Generated by Django 6.0 on 2026-01-03 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_by', models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider')], max_length=20)),
                ('reason', models.CharField(choices=[('service_not_completed', 'Service Not Completed'), ('quality_issue', 'Quality Issue'), ('provider_no_show', 'Provider No-Show'), ('late_delivery', 'Late Delivery'), ('wrong_service', 'Wrong Service Delivered'), ('payment_issue', 'Payment Issue'), ('other', 'Other')], max_length=50)),
                ('complaint', models.TextField(help_text='Detailed description of the issue')),
                ('evidence', models.TextField(blank=True, help_text='Evidence or screenshots description')),
                ('provider_response', models.TextField(blank=True, null=True)),
                ('provider_responded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('appealed', 'Appealed'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution', models.CharField(choices=[('pending', 'Pending Decision'), ('release_to_provider', 'Release Funds to Provider'), ('refund_customer', 'Refund Customer'), ('partial_split', 'Partial Split'), ('hold_pending', 'Hold Pending Investigation')], default='pending', max_length=30)),
                ('admin_decision', models.TextField(blank=True, help_text="Admin's reasoning for resolution")),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_text', models.TextField(blank=True, null=True)),
                ('appealed_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_decision', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Support staff assigned to this dispute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('filer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_filed', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='orders.order')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='orders_disp_created_a015c5_idx'), models.Index(fields=['status'], name='orders_disp_status_a7bf34_idx'), models.Index(fields=['order'], name='orders_disp_order_i_25ca25_idx')],
            },
        ),
    ]
