# Generated by Django 5.2 on 2026-03-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('seller_completed', 'Seller Marked Complete'), ('completed', 'Buyer Confirmed - Complete'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
