# Generated by Django 6.0 on 2025-12-25 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Jollof Rice + Chicken, Gel Nails', max_length=200)),
                ('description', models.TextField(help_text='Full description of the product/service')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in NGN', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='listings/')),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck if sold out or paused')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='services.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product/Service Listing',
                'verbose_name_plural': 'Product/Service Listings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='services_li_categor_565238_idx'), models.Index(fields=['is_available'], name='services_li_is_avai_ab35cf_idx'), models.Index(fields=['vendor'], name='services_li_vendor__ccb2aa_idx')],
            },
        ),
    ]
