# Generated by Django 6.0 on 2025-12-25 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in NGN', max_digits=10)),
                ('status', models.CharField(choices=[('in_escrow', 'In Escrow'), ('released', 'Released to Wallet'), ('withdrawn', 'Withdrawn to Bank')], default='in_escrow', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout Transaction',
                'verbose_name_plural': 'Payout Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor'], name='services_tr_vendor__37acfc_idx'), models.Index(fields=['status'], name='services_tr_status_b8e220_idx')],
            },
        ),
    ]
