# Generated by Django 6.0 on 2025-12-25 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('services', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='orders.order'),
        ),
    ]
