# Generated by Django 5.2 on 2026-02-17 12:51

import studex.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_transaction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[studex.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='listings/', validators=[studex.validators.validate_image]),
        ),
    ]
