# Generated by Django 5.2 on 2026-03-14 15:47

import studex.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_category_image_alter_listing_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('service', 'Service'), ('product', 'Product'), ('food', 'Food')], default='service', help_text='Type of listing — affects inventory tracking', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Current stock. Auto-marks unavailable when it reaches 0.'),
        ),
        migrations.AddField(
            model_name='listing',
            name='track_inventory',
            field=models.BooleanField(default=False, help_text='Enable stock tracking (recommended for food and physical products)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/', validators=[studex.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Admin must tick this to make listing visible in shop'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listing_type'], name='services_li_listing_cd7f51_idx'),
        ),
    ]
